Blacklisted-Names:
  - "Notch"
  - "Hero"
  - "Herobrine"
  - "Hypixel"
  - "PornHub"
  - "Nigga"
  - "Cum"
  - "sex"
  - "Pussy"
  - "Fuck"
  - "noob"
  - "Yousuck"
  - "balls"
  - "retard"
  - "couilles"
  - "seins"
  - "penis"
  - "connard"
  - "1234"
Whitelist-Names:
  Enable: false
  Whitelisted-Names:
    - "Owner"
    - "keyboard13"
    - "Prism"
Messages:
  Kick-Message: "&cThis Username is not allowed!"
  No-Permission: "&cYou do not have permission to run this command."
  Reload-Message: "&aConfig Reloaded."
  Invalid-Syntax: "&cInvalid Syntax!"
