name: NameVerif
version: ${project.version}
main: com.carpour.nameverif.Main
api-version: 1.13
authors: [ Prism3 ]
description: Simple plugin that checks for inappropriate player names before joining your Server.
softdepend: [Geyser, floodgate]
website: prism3.me
commands:
  nameverif:
    description: Plugin Command.
permissions:
  nameverif.admin:
    description: Ability to toggle, add, remove, and list names from the config and reloading it.
    default: op
  nameverif.bypass:
    description: Bypass the Checkers.