name: NameVerif
version: ${project.version}
main: me.prism3.nameverif.Main
api-version: 1.13
authors: [ Prism3 ]
description: Simple plugin that checks for inappropriate player names before joining your Server.
softdepend: [Geyser, floodgate]
website: prism3.me
commands:
  nameverif:
    description: Plugin Command.
  nameverif add-blacklist:
    description: Add a name into the blacklist
  nameverif add-whitelist:
    description: Add a name into the whitelist
  nameverif list-blacklist:
    description: list-whitelist
  nameverif reload:
    description: Reload the plugin config
  nameverif remove-blacklist:
    description: Remove a name from the blacklist
  nameverif remove-whitelist:
    description: Remove a name from the whitelist
  nameverif toggle:
    description: Toggle the whitelist mode
permissions:
  nameverif.admin:
    description: Ability to toggle, add, remove, and list names from the config and reloading it.
    default: op
  nameverif.bypass:
    description: Bypass the Checkers.
    default: op